### ISSUE TITLE
Renesas rcar-h3 Salvator-X board

### ISSUE THREAD

**Issue by Daparrag** [xvisor/xvisor#109]
Hi Guys.

Hoping  this is not an inappropriate question. 

I had tried to find some documentation about the Renesas rcar-h3 Salvator-X board in the 2.11 release but I couldn't find it. 

Any Idea of where it should be.  

If you currently are working on that.  I would like to be part of the development. would you please give me some advice about the current status of this development. 

Thanks.

**Comment by avpatel** [comment]
We have everything for RCAR H3 in-place but we were not able to try on real HW due to lack of board.

You are welcome to try on real board and submit patches to xvisor-devel@googlegroups.com

You can also submit README for RCAR H3 under docs/arm directory.

The steps on RCAR H3 will be similar to Znqmp so you can refer docs/arm/zynqmp-zcu102.txt

**Comment by Daparrag** [comment]
Hi avpatel.

Thanks for you answer. 

Im try to run Xvisor on RCAR H3 but I stoped at the point 6
```
[6. Make U-Boot compatible uvmm.bin for use with bootm command]
  # mkimage -A arm64 -O linux -T kernel -C none -a 0x00080000 -e 0x00080000 -n Xvisor -d build/vmm.bin build/uvmm.bin

```
since I don't know from where these ```-a 0x00080000 -e 0x00080000``` two addresses are comming from. Could you please tell me if you have any idea or where is a reference for those values in the RCAR H3  because I couldn't fine anything in the board manual.  

thank you.

**Comment by Daparrag** [comment]
Hi avpatel.

 I Resolve this issue. 
Im planning  submit README for RCAR H3 under docs/arm directory soon.

Thank you.
