### ISSUE TITLE
big.LITTLE chip

### ISSUE THREAD

**Issue by shawchina** [xvisor/xvisor#130]
hi, 
Does xvisor support big.LITTLE chip ? like 4x53 and 2xA72.

**Comment by avpatel** [comment]
We have not tried Xvisor on any big.Little SoC till now due to lack of availability of development board.

Theoretically, we can support big.Little with some fixes.

The biggest plus for Xvisor on big.Little is that we don't move VCPUs across host CPUs unless explicitly done by user. This means users just need to create Guest/VM with appropriate host CPU assignment.

Regards,
Anup

**Comment by shawchina** [comment]
I get it, Thanks for your answer ! I will read more Xvisor source code.
